name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: src/global.json

      - name: Test
        run: ./src/build.sh --target Test
        env:
          NuGetApiKey: ${{ secrets.NugetKey }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack
        run: ./src/build.sh --target Pack
        env:
          NuGetApiKey: ${{ secrets.NugetKey }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (nupkg)
        uses: actions/upload-artifact@v3
        with:
          name: nupkgs
          path: |
            Artifacts/*.nupkg
            Artifacts/*.snupkg

