name: Test

on:
  push:
    branches:
    - master
  pull_request: 

jobs:
  # Test on ubuntu
  build-test-ubuntu:
   runs-on: ubuntu-latest

   # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
    
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
       with:
         submodules: 'recursive'
         fetch-depth: 0

     - name: Setup .NET SDKs
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: |
           6.0.x
           7.0.x

     - name: Run NUKE
       run: ./src/build.sh --target Test
       env:
         NuGetApiKey: ${{ secrets.NugetKey }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Test Report
       uses: dorny/test-reporter@v1
       if: always()
       with:
         name: DotNET Tests
         path: "./TestResults/*.trx"                            
         reporter: dotnet-trx
         fail-on-error: true